// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaymHqxx1-tDBSaHN8Q5lvp7X2AcBFJsE',
    appId: '1:859134129636:ios:5e9c4de3aca43233dd83f1',
    messagingSenderId: '859134129636',
    projectId: 'ventify-project',
    storageBucket: 'ventify-project.firebasestorage.app',
    iosBundleId: 'com.example.ventifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaymHqxx1-tDBSaHN8Q5lvp7X2AcBFJsE',
    appId: '1:859134129636:ios:5e9c4de3aca43233dd83f1',
    messagingSenderId: '859134129636',
    projectId: 'ventify-project',
    storageBucket: 'ventify-project.firebasestorage.app',
    iosBundleId: 'com.example.ventifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5MDFH3atQnlIyUWcJ3XyOqGYp6jIgcrg',
    appId: '1:859134129636:web:a63b13d651822e66dd83f1',
    messagingSenderId: '859134129636',
    projectId: 'ventify-project',
    authDomain: 'ventify-project.firebaseapp.com',
    storageBucket: 'ventify-project.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5MDFH3atQnlIyUWcJ3XyOqGYp6jIgcrg',
    appId: '1:859134129636:web:a63b13d651822e66dd83f1',
    messagingSenderId: '859134129636',
    projectId: 'ventify-project',
    authDomain: 'ventify-project.firebaseapp.com',
    storageBucket: 'ventify-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQUDUl70xFcm0w10wh4Ewe-sdbkSqagYY',
    appId: '1:859134129636:android:e8445583e2892419dd83f1',
    messagingSenderId: '859134129636',
    projectId: 'ventify-project',
    storageBucket: 'ventify-project.firebasestorage.app',
  );

}